pipeline:
  name: Build and Deploy Auth Service
  identifier: Build_and_Deploy_auth_service
  projectIdentifier: default_project
  orgIdentifier: default
  tags:
    application: auth-service
  template:
    templateRef: Otterworks_Build_Deploy_Template
    versionLabel: v2
    templateInputs:
      properties:
        ci:
          codebase:
            connectorRef: KGS_AI_Github
            repoName: otterworks
            build: <+input>
      variables:
      - name: servicenow_incident_number
        type: String
        value: <+input>.default("")
      - name: aws_connector
        type: String
        value: <+input>.default("KGS_AWS_ALERT_environment")
      - name: aws_account_id
        type: String
        value: <+input>.default("178707646889")
      - name: aws_region
        type: String
        value: <+input>.default("us-east-1")
      - name: ecr_image_path
        type: String
        value: otterworks/auth-service
      - name: service_workspace
        type: String
        value: ./services/auth-service
      - name: build_context
        type: String
        value: ./services/auth-service
      - name: dockerfile_path
        type: String
        value: ./services/auth-service/Dockerfile
      - name: build_image
        type: String
        value: gradle:8.6-jdk17
      - name: sonar_project_key
        type: String
        value: <+input>.default("Koniag-gs")
      - name: delegate_selector
        type: String
        value: <+input>.default("terraform-delegate")
      - name: servicenow_connector
        type: String
        value: <+input>.default("koniaggovernmentservicesllcdemo1")
      - name: build_command
        type: String
        value: gradle bootJar --no-daemon
      - name: test_command
        type: String
        value: gradle test --no-daemon
      - name: static_analysis_command
        type: String
        value: gradle spotlessCheck --no-daemon
      - name: test_intelligence
        type: String
        value: 'false'
      stages:
      - stage:
          identifier: Provision_Infra
          type: IACM
          spec:
            workspace: koniagcognitionharnessworkspace
      - stage:
          identifier: Deploy_to_Dev
          type: Deployment
          spec:
            service:
              serviceRef: otterworks_authservice
              serviceInputs:
                serviceDefinition:
                  type: NativeHelm
                  spec:
                    artifacts:
                      primary:
                        primaryArtifactRef: auth_service
            environment:
              environmentRef: alert_dev
              gitBranch: harness-dev-env-patch
              infrastructureDefinitions:
              - identifier: alertdevinfra_nativehelm
